services:
  db:
    image: postgres:latest
    container_name: smart_track_psql_db
    restart: always
    env_file: backend/app/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_smart_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    env_file:
      - backend/app/.env
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  postgres_smart_data:
